spring:
  application:
    name: tang

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # 매퍼 파일 경로
  type-aliases-package: org.kernel360.tang.model     # 모델 클래스 경로
  type-handlers-package: org.kernel360.tang.mybatis.typeHandler